### ISSUE TITLE
Does ProMS support multi-class feature selection? 

### ISSUE THREAD

**Issue by dbyzy** [bzhanglab/proms#5]
Thank you for the ProMS. It is really a nice tool for feature selection. 
In the data preparation section of the docs, 

> For binary classification task, the valid label values are either 0 (negative class) or 1 (positive class). For surival analysis task, columns for both event indicator and survival/censoring time should be provided.

I am wondering if ProMS supports multi-class feature selection, i.e., more than two classifications, and how should we prepare the Label data. 

Thanks in advance.

**Comment by zhiaos** [comment]
currently it does not support multi-class task, something we might look to add in the future.

**Comment by dbyzy** [comment]
Many thanks for your reply :)
